apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"projectcontour"}}
  creationTimestamp: "2025-11-16T17:53:38Z"
  labels:
    kubernetes.io/metadata.name: projectcontour
  name: projectcontour
  resourceVersion: "6869527"
  uid: ab59d971-2d01-4ce5-9997-b06dd1f6fd23
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
