{
 "title": "Alloy / Controller",
 "tags": [ "alloy-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "logs_datasource", "label": "Logs Data Source", "query": "grafana-clickhouse-datasource" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(alloy_component_controller_running_components, cluster)\n"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{cluster=~\"$cluster\"}, namespace)\n"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{cluster=~\"$cluster\", namespace=~\"$namespace\"}, job)\n"
    }
   },
   { "name": "filters" },
   {
    "name": "groupby",
    "label": "Group by",
    "query": "instance,component_path,component_id,controller_path,health_type,job,namespace,cluster,pod"
   }
  ]
 },
 "panels": [
  {
   "title": "Running instances",
   "type": "stat",
   "description": "The number of Alloy instances whose metrics are being sent and reported.\n",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "instances" } },
   "targets": [
    {
     "expr": "count(group(alloy_component_controller_running_components{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}) by (instance))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running components",
   "type": "stat",
   "description": "The number of running components across all running instances.\n",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "components" } },
   "targets": [
    {
     "expr": "sum(alloy_component_controller_running_components{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall component health",
   "type": "stat",
   "description": "The percentage of components which are in a healthy state.\n",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(alloy_component_controller_running_components{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\",health_type=\"healthy\"}) /\nsum(alloy_component_controller_running_components{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Components by health",
   "type": "bargauge",
   "description": "Breakdown of components by health across all running instances.\n\n* Healthy: components have been evaluated completely and are reporting themselves as healthy.\n* Unhealthy: Components either could not be evaluated or are reporting themselves as unhealthy.\n* Unknown: A component has been created but has not yet been started.\n* Exited: A component has exited. It will not return to the running state.\n\nMore information on a component's health state can be retrieved using\nthe Alloy UI.\n\nNote that components may be in a degraded state even if they report\nthemselves as healthy. Use component-specific dashboards and alerts\nto observe detailed information about the behavior of a component.\n",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(alloy_component_controller_running_components{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", health_type=\"healthy\"}) or vector(0)\n",
     "legendFormat": "Healthy"
    },
    {
     "expr": "sum(alloy_component_controller_running_components{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", health_type=\"unhealthy\"}) or vector(0)\n",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "sum(alloy_component_controller_running_components{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", health_type=\"unknown\"}) or vector(0)\n",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sum(alloy_component_controller_running_components{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", health_type=\"exited\"}) or vector(0)\n",
     "legendFormat": "Exited"
    }
   ]
  },
  {
   "title": "Component evaluation rate",
   "type": "timeseries",
   "description": "The frequency at which components get updated.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (${groupby}) (rate(alloy_component_evaluation_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Component evaluation time",
   "type": "timeseries",
   "description": "The percentiles for how long it takes to complete component evaluations.\n\nComponent evaluations must complete for components to have the latest\narguments. The longer the evaluations take, the slower it will be to\nreconcile the state of components.\n\nIf evaluation is taking too long, consider sharding your components to\ndeal with smaller amounts of data and reuse data as much as possible.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(alloy_component_evaluation_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])))\nor\nhistogram_quantile(0.99, sum by (le) (rate(alloy_component_evaluation_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])))\n",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(alloy_component_evaluation_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])))\nor\nhistogram_quantile(0.50, sum by (le) (rate(alloy_component_evaluation_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])))\n",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "(\n  histogram_sum(sum(rate(alloy_component_evaluation_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))) /\n  histogram_count(sum(rate(alloy_component_evaluation_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])))\n)\nor\n(\n  sum(rate(alloy_component_evaluation_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) /\n  sum(rate(alloy_component_evaluation_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n)\n",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Slow components evaluation times",
   "type": "timeseries",
   "description": "The maximum duration of slow component evaluations over time.\n\nThis shows components that took longer than 1 minute to evaluate. Ideally, no component \nshould take more than 1 minute to evaluate. The components displayed in this chart\nmay be a sign of a problem with the pipeline or performance issues.\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(alloy_component_evaluation_slow_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])\n",
     "legendFormat": "{{instance}} {{controller_path}} {{component_id}}"
    }
   ]
  },
  {
   "title": "Component evaluation histogram",
   "type": "heatmap",
   "description": "Detailed histogram view of how long component evaluations take.\n\nThe goal is to design your config so that evaluations take as little\ntime as possible; under 100ms is a good goal.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(alloy_component_evaluation_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\nor ignoring (le)\nsum by (le) (increase(alloy_component_evaluation_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Component dependency wait histogram",
   "type": "heatmap",
   "description": "Detailed histogram of how long components wait to be evaluated after their dependency is updated.\n\nThe goal is to design your config so that most of the time components do not\nqueue for long; under 10ms is a good goal.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(alloy_component_dependencies_wait_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\nor ignoring (le)\nsum by (le) (increase(alloy_component_dependencies_wait_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}
{
 "title": "Alloy / OpenTelemetry",
 "tags": [ "alloy-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "logs_datasource", "label": "Logs Data Source", "query": "grafana-clickhouse-datasource" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(alloy_component_controller_running_components, cluster)\n"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{cluster=~\"$cluster\"}, namespace)\n"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{cluster=~\"$cluster\", namespace=~\"$namespace\"}, job)\n"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}, instance)\n"
    }
   },
   { "name": "filters" },
   {
    "name": "groupby",
    "label": "Group by",
    "query": "instance,receiver,transport,exporter,processor,component_id,otel_signal,otel_scope_name,job,namespace,cluster,pod"
   }
  ]
 },
 "panels": [
  { "title": "Receivers [otelcol.receiver.*]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Accepted metric points",
   "type": "timeseries",
   "description": "Number of metric points successfully pushed into the pipeline.\n",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(otelcol_receiver_accepted_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Refused metric points",
   "type": "timeseries",
   "description": "Number of metric points that could not be pushed into the pipeline.\n",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(otelcol_receiver_refused_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted logs",
   "type": "timeseries",
   "description": "Number of log records successfully pushed into the pipeline.\n",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(otelcol_receiver_accepted_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Refused logs",
   "type": "timeseries",
   "description": "Number of log records that could not be pushed into the pipeline.\n",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(otelcol_receiver_refused_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted spans",
   "type": "timeseries",
   "description": "Number of spans successfully pushed into the pipeline.\n",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(otelcol_receiver_accepted_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Refused spans",
   "type": "timeseries",
   "description": "Number of spans that could not be pushed into the pipeline.\n",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(otelcol_receiver_refused_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC server duration",
   "type": "heatmap",
   "description": "The duration of inbound RPCs for otelcol.receiver.* components.\n",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (le) (increase(rpc_server_duration_milliseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\", component_id=~\"otelcol.receiver.*\"}[$__rate_interval]))\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP server duration",
   "type": "heatmap",
   "description": "The duration of inbound HTTP requests for otelcol.receiver.* components.\n",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_server_duration_milliseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\", component_id=~\"otelcol.receiver.*\"}[$__rate_interval]))\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Batching [otelcol.processor.batch]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Number of units in the batch",
   "type": "heatmap",
   "description": "Number of spans, metric datapoints, or log lines in a batch\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le) (increase(otelcol_processor_batch_batch_send_size_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Distinct metadata values",
   "type": "timeseries",
   "description": "Number of distinct metadata value combinations being processed\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (otelcol_processor_batch_metadata_cardinality{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeout trigger",
   "type": "timeseries",
   "description": "Number of times the batch was sent due to a timeout trigger\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(otelcol_processor_batch_timeout_trigger_send_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Exporters [otelcol.exporter.*]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Exported metric points",
   "type": "timeseries",
   "description": "Number of metric points successfully sent to destination.\n",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(otelcol_exporter_sent_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed metric points",
   "type": "timeseries",
   "description": "Number of metric points that failed to be sent to destination.\n",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(otelcol_exporter_send_failed_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exported logs",
   "type": "timeseries",
   "description": "Number of log records successfully sent to destination.\n",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(otelcol_exporter_sent_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed logs",
   "type": "timeseries",
   "description": "Number of log records that failed to be sent to destination.\n",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(otelcol_exporter_send_failed_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exported spans",
   "type": "timeseries",
   "description": "Number of spans successfully sent to destination.\n",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(otelcol_exporter_sent_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed spans",
   "type": "timeseries",
   "description": "Number of spans that failed to be sent to destination.\n",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(otelcol_exporter_send_failed_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC client duration",
   "type": "heatmap",
   "description": "The duration of outbound RPCs for otelcol.exporter.* components.\n",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum by (le) (increase(rpc_client_duration_milliseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\", component_id=~\"otelcol.exporter.*\"}[$__rate_interval]))\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP client duration",
   "type": "heatmap",
   "description": "The duration of outbound HTTP requests for otelcol.exporter.* components.\n",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 40 },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_client_duration_milliseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\", component_id=~\"otelcol.exporter.*\"}[$__rate_interval]))\n",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}
{
 "title": "Alloy / OTel Engine Overview",
 "description": "Overview of the OpenTelemetry (OTel) engine running inside Alloy.",
 "tags": [ "alloy-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "logs_datasource", "label": "Logs Data Source", "query": "grafana-clickhouse-datasource" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(otelcol_process_uptime_seconds_total, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(otelcol_process_uptime_seconds_total{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(otelcol_process_uptime_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "groupby",
    "label": "Group by",
    "query": "instance,receiver,transport,exporter,processor,otel_signal,otel_scope_name,job,namespace,cluster,pod"
   },
   { "name": "filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods count",
   "type": "stat",
   "description": "Current number of pods with OTel engine metrics.\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(otelcol_process_uptime_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"})\n",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Recently started by ${groupby}",
   "type": "timeseries",
   "description": "Count of series with process uptime under 60 seconds, grouped by the selected dimension.\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count by(${groupby}) (otelcol_process_uptime_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"} < 60)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receivers SR",
   "type": "timeseries",
   "description": "Receiver success rate for each signal type.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n/\n(\n    sum(rate(otelcol_receiver_accepted_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n    +\n    (sum(rate(otelcol_receiver_refused_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) or vector(0))\n)\n",
     "legendFormat": "spans"
    },
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n/\n(\n    sum(rate(otelcol_receiver_accepted_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n    +\n    (sum(rate(otelcol_receiver_refused_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) or vector(0))\n)\n",
     "legendFormat": "metric points"
    },
    {
     "expr": "sum(rate(otelcol_receiver_accepted_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n/\n(\n    sum(rate(otelcol_receiver_accepted_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n    +\n    (sum(rate(otelcol_receiver_refused_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) or vector(0))\n)\n",
     "legendFormat": "log records"
    }
   ]
  },
  {
   "title": "Exporters SR",
   "type": "timeseries",
   "description": "Exporter success rate for each signal type.\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n/\n(\n    sum(rate(otelcol_exporter_sent_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n    +\n    (sum(rate(otelcol_exporter_enqueue_failed_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) or vector(0))\n    +\n    (sum(rate(otelcol_exporter_send_failed_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) or vector(0))\n)\n",
     "legendFormat": "spans"
    },
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n/\n(\n    sum(rate(otelcol_exporter_sent_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n    +\n    (sum(rate(otelcol_exporter_enqueue_failed_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) or vector(0))\n    +\n    (sum(rate(otelcol_exporter_send_failed_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) or vector(0))\n)\n",
     "legendFormat": "metric points"
    },
    {
     "expr": "sum(rate(otelcol_exporter_sent_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n/\n(\n    sum(rate(otelcol_exporter_sent_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n    +\n    (sum(rate(otelcol_exporter_enqueue_failed_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) or vector(0))\n    +\n    (sum(rate(otelcol_exporter_send_failed_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) or vector(0))\n)\n",
     "legendFormat": "log records"
    }
   ]
  },
  {
   "title": "Spans & Traces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receiver: Total accepted & refused",
     "type": "timeseries",
     "description": "Total rate of accepted and refused spans across all receivers.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_receiver_accepted_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "accepted"
      },
      {
       "expr": "sum(rate(otelcol_receiver_refused_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "refused"
      }
     ]
    },
    {
     "title": "Receiver: Accepted by ${groupby}",
     "type": "timeseries",
     "description": "Accepted and refused spans rates broken down by the selected dimension.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_receiver_accepted_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{${groupby}}} accepted"
      },
      {
       "expr": "sum by(${groupby}) (rate(otelcol_receiver_refused_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{${groupby}}} refused"
      }
     ]
    },
    {
     "title": "Receiver: Refused by ${groupby}",
     "type": "timeseries",
     "description": "Refused spans rate broken down by the selected dimension.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_receiver_refused_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exporter: Total sent & failed",
     "type": "timeseries",
     "description": "Total rate of sent, send-failed, and enqueue-failed spans across all exporters.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_exporter_sent_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "sent"
      },
      {
       "expr": "sum(rate(otelcol_exporter_send_failed_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "send failed"
      },
      {
       "expr": "sum(rate(otelcol_exporter_enqueue_failed_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "enqueue failed"
      }
     ]
    },
    {
     "title": "Exporter: Sent by ${groupby}",
     "type": "timeseries",
     "description": "Sent spans rate broken down by the selected dimension.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_exporter_sent_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exporter: Failed by ${groupby}",
     "type": "timeseries",
     "description": "Send-failed and enqueue-failed spans rates broken down by the selected dimension.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_exporter_send_failed_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{${groupby}}} send failed"
      },
      {
       "expr": "sum by(${groupby}) (rate(otelcol_exporter_enqueue_failed_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{${groupby}}} enqueue failed"
      }
     ]
    },
    {
     "title": "Exporter: Queue utilization by ${groupby}",
     "type": "timeseries",
     "description": "Exporter send queue usage as a fraction of capacity. Values approaching 1 indicate backpressure and risk of data loss.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (otelcol_exporter_queue_size{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", data_type=\"traces\"})\n/\nclamp_min(sum by(${groupby}) (otelcol_exporter_queue_capacity{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", data_type=\"traces\"}), 1)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receiver: Total accepted & refused",
     "type": "timeseries",
     "description": "Total rate of accepted and refused metric points across all receivers.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_receiver_accepted_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "accepted"
      },
      {
       "expr": "sum(rate(otelcol_receiver_refused_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "refused"
      }
     ]
    },
    {
     "title": "Receiver: Accepted by ${groupby}",
     "type": "timeseries",
     "description": "Accepted and refused metric points rates broken down by the selected dimension.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_receiver_accepted_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{${groupby}}} accepted"
      },
      {
       "expr": "sum by(${groupby}) (rate(otelcol_receiver_refused_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{${groupby}}} refused"
      }
     ]
    },
    {
     "title": "Receiver: Refused by ${groupby}",
     "type": "timeseries",
     "description": "Refused metric points rate broken down by the selected dimension.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_receiver_refused_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exporter: Total sent & failed",
     "type": "timeseries",
     "description": "Total rate of sent, send-failed, and enqueue-failed metric points across all exporters.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_exporter_sent_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "sent"
      },
      {
       "expr": "sum(rate(otelcol_exporter_send_failed_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "send failed"
      },
      {
       "expr": "sum(rate(otelcol_exporter_enqueue_failed_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "enqueue failed"
      }
     ]
    },
    {
     "title": "Exporter: Sent by ${groupby}",
     "type": "timeseries",
     "description": "Sent metric points rate broken down by the selected dimension.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_exporter_sent_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exporter: Failed by ${groupby}",
     "type": "timeseries",
     "description": "Send-failed and enqueue-failed metric points rates broken down by the selected dimension.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_exporter_send_failed_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{${groupby}}} send failed"
      },
      {
       "expr": "sum by(${groupby}) (rate(otelcol_exporter_enqueue_failed_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{${groupby}}} enqueue failed"
      }
     ]
    },
    {
     "title": "Exporter: Queue utilization by ${groupby}",
     "type": "timeseries",
     "description": "Exporter send queue usage as a fraction of capacity. Values approaching 1 indicate backpressure and risk of data loss.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (otelcol_exporter_queue_size{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", data_type=\"metrics\"})\n/\nclamp_min(sum by(${groupby}) (otelcol_exporter_queue_capacity{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", data_type=\"metrics\"}), 1)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receiver: Total accepted & refused",
     "type": "timeseries",
     "description": "Total rate of accepted and refused log records across all receivers.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_receiver_accepted_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "accepted"
      },
      {
       "expr": "sum(rate(otelcol_receiver_refused_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "refused"
      }
     ]
    },
    {
     "title": "Receiver: Accepted by ${groupby}",
     "type": "timeseries",
     "description": "Accepted and refused log records rates broken down by the selected dimension.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_receiver_accepted_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{${groupby}}} accepted"
      },
      {
       "expr": "sum by(${groupby}) (rate(otelcol_receiver_refused_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{${groupby}}} refused"
      }
     ]
    },
    {
     "title": "Receiver: Refused by ${groupby}",
     "type": "timeseries",
     "description": "Refused log records rate broken down by the selected dimension.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_receiver_refused_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exporter: Total sent & failed",
     "type": "timeseries",
     "description": "Total rate of sent, send-failed, and enqueue-failed log records across all exporters.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_exporter_sent_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "sent"
      },
      {
       "expr": "sum(rate(otelcol_exporter_send_failed_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "send failed"
      },
      {
       "expr": "sum(rate(otelcol_exporter_enqueue_failed_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "enqueue failed"
      }
     ]
    },
    {
     "title": "Exporter: Sent by ${groupby}",
     "type": "timeseries",
     "description": "Sent log records rate broken down by the selected dimension.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_exporter_sent_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exporter: Failed by ${groupby}",
     "type": "timeseries",
     "description": "Send-failed and enqueue-failed log records rates broken down by the selected dimension.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_exporter_send_failed_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{${groupby}}} send failed"
      },
      {
       "expr": "sum by(${groupby}) (rate(otelcol_exporter_enqueue_failed_log_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{${groupby}}} enqueue failed"
      }
     ]
    },
    {
     "title": "Exporter: Queue utilization by ${groupby}",
     "type": "timeseries",
     "description": "Exporter send queue usage as a fraction of capacity. Values approaching 1 indicate backpressure and risk of data loss.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (otelcol_exporter_queue_size{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", data_type=\"logs\"})\n/\nclamp_min(sum by(${groupby}) (otelcol_exporter_queue_capacity{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", data_type=\"logs\"}), 1)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Processing & Batching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processor throughput",
     "type": "timeseries",
     "description": "Incoming vs outgoing items across all processors. A gap between the two may indicate items being dropped or filtered.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_processor_incoming_items_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
       "legendFormat": "incoming"
      },
      {
       "expr": "sum(rate(otelcol_processor_outgoing_items_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
       "legendFormat": "outgoing"
      }
     ]
    },
    {
     "title": "Processor throughput by ${groupby}",
     "type": "timeseries",
     "description": "Incoming vs outgoing items broken down by the selected dimension.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_processor_incoming_items_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
       "legendFormat": "{{${groupby}}} incoming"
      },
      {
       "expr": "sum by(${groupby}) (rate(otelcol_processor_outgoing_items_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
       "legendFormat": "{{${groupby}}} outgoing"
      }
     ]
    },
    {
     "title": "Processor refused by ${groupby}",
     "type": "timeseries",
     "description": "Items refused by processors, broken down by signal type and selected dimension.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_processor_refused_spans_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
       "legendFormat": "{{${groupby}}} spans"
      },
      {
       "expr": "sum by(${groupby}) (rate(otelcol_processor_refused_metric_points_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
       "legendFormat": "{{${groupby}}} metric points"
      }
     ]
    },
    {
     "title": "Batch send size",
     "type": "heatmap",
     "description": "Distribution of batch sizes when sent. Works with both batching approaches:\nthe batch processor (processor/batch) and the exporter sending_queue batch (sending_queue.batch).\nWhichever is active will populate this panel.\nRequires \"normal\" telemetry level.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 120 },
     "targets": [
      {
       "expr": "sum by (le) (increase(otelcol_exporter_queue_batch_send_size_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\nor\nsum by (le) (increase(otelcol_processor_batch_batch_send_size_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Batch send triggers by ${groupby}",
     "type": "timeseries",
     "description": "How batches are flushed: by reaching the size limit or by timeout. Mostly timeout triggers may indicate low throughput or a large batch size setting. Only available with the batch processor; the exporter sending_queue batch does not emit trigger metrics. Requires \"normal\" telemetry level.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(${groupby}) (rate(otelcol_processor_batch_batch_size_trigger_send_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
       "legendFormat": "{{${groupby}}} size trigger"
      },
      {
       "expr": "sum by(${groupby}) (rate(otelcol_processor_batch_timeout_trigger_send_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
       "legendFormat": "{{${groupby}}} timeout trigger"
      }
     ]
    },
    {
     "title": "Batch metadata cardinality by ${groupby}",
     "type": "timeseries",
     "description": "Number of distinct metadata value combinations being processed. High cardinality increases memory usage and may hit the metadata_cardinality_limit. Only available with the batch processor; the exporter sending_queue batch does not emit this metric. Requires \"normal\" telemetry level.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 120 },
     "targets": [
      {
       "expr": "sum by(${groupby}) (otelcol_processor_batch_metadata_cardinality{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"})\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "CPU cores used by OTel engine processes. 1.0 = 100% of one core.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(sum by(instance) (rate(otelcol_process_cpu_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])))\n",
       "legendFormat": "average"
      },
      {
       "expr": "sum by(instance) (rate(otelcol_process_cpu_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory RSS",
     "type": "timeseries",
     "description": "Resident set size (physical memory) used by OTel engine processes.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(sum by(instance) (otelcol_process_memory_rss_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}))\n",
       "legendFormat": "average"
      },
      {
       "expr": "sum by(instance) (otelcol_process_memory_rss_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"})\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Go allocation rate",
     "type": "timeseries",
     "description": "Rate of heap memory allocation. High allocation rates often lead to GC pressure.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg(sum by(instance) (rate(otelcol_process_runtime_total_alloc_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])))\n",
       "legendFormat": "average"
      },
      {
       "expr": "sum by(instance) (rate(otelcol_process_runtime_total_alloc_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Grafana Cloud Connector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unique hosts tracked",
     "type": "timeseries",
     "description": "Number of unique hosts identified by the grafanacloud connector for Application Observability billing. Only available when the grafanacloud connector is configured.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 150 },
     "targets": [
      {
       "expr": "sum by(${groupby}) (otelcol_grafanacloud_host_count_ratio{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"})\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Datapoints sent rate",
     "type": "timeseries",
     "description": "Total rate of datapoints sent to Grafana Cloud by the grafanacloud connector. Only available when the grafanacloud connector is configured.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_grafanacloud_datapoint_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))\n",
       "legendFormat": "total"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Alloy / Resources",
 "tags": [ "alloy-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "logs_datasource", "label": "Logs Data Source", "query": "grafana-clickhouse-datasource" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(alloy_component_controller_running_components, cluster)\n"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{cluster=~\"$cluster\"}, namespace)\n"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{cluster=~\"$cluster\", namespace=~\"$namespace\"}, job)\n"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}, instance)\n"
    }
   },
   { "name": "filters" },
   {
    "name": "groupby",
    "label": "Group by",
    "query": "instance,job,namespace,cluster,pod"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage of the Alloy process relative to 1 CPU core.\n\nFor example, 100% means using one entire CPU core.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(alloy_resources_process_cpu_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (RSS)",
   "type": "timeseries",
   "description": "Resident memory size of the Alloy process.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (alloy_resources_process_resident_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage collections",
   "type": "timeseries",
   "description": "Rate at which the Alloy process performs garbage collections.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (\n  rate(go_gc_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[5m])\n  and on(instance)\n  alloy_build_info{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Number of goroutines which are running in parallel. An infinitely\ngrowing number of these indicates a goroutine leak.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (\n  go_goroutines{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}\n  and on(instance)\n  alloy_build_info{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (heap in use)",
   "type": "timeseries",
   "description": "Heap memory currently in use by the Alloy process.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (\n  go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}\n  and on(instance)\n  alloy_build_info{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network receive bandwidth",
   "type": "timeseries",
   "description": "Rate of data received across all network interfaces for the machine\nAlloy is running on.\n\nData shown here is across all running processes and not exclusive to\nthe running Alloy process.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(alloy_resources_machine_rx_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network send bandwidth",
   "type": "timeseries",
   "description": "Rate of data sent across all network interfaces for the machine\nAlloy is running on.\n\nData shown here is across all running processes and not exclusive to\nthe running Alloy process.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (rate(alloy_resources_machine_tx_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}