{
 "title": "Simple ClickHouse OTel Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "ClickHouse instance", "query": "grafana-clickhouse-datasource" },
   {
    "name": "serviceName",
    "label": "Service Name",
    "query": "SELECT DISTINCT ServiceName FROM otel_traces"
   },
   {
    "name": "trace_id",
    "label": "Trace Id",
    "query": "SELECT DISTINCT TraceId FROM otel_traces WHERE ParentSpanId = '' LIMIT 100"
   }
  ]
 },
 "panels": [
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traces per Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeInterval(Timestamp) as time,\r\n  ServiceName,\r\n  count() as ` `\r\nFROM otel_traces\r\nWHERE\r\n  $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id)\r\n  AND $__timeFilter(Timestamp)\r\n  AND ServiceName IN (${serviceName:singlequote})\r\nGROUP BY ServiceName, time\r\nORDER BY time ASC\r\nLIMIT 100000\r\n"
    }
   ]
  },
  {
   "title": "Service Performance - p99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeInterval(Timestamp) as time,\r\n  ServiceName,\r\n  quantile(0.99)(Duration)/1000000 AS p99\r\nFROM otel_traces\r\nWHERE\r\n  $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id)\r\n  AND $__timeFilter(Timestamp)\r\n  AND ( Timestamp  >= $__fromTime AND Timestamp <= $__toTime )\r\n  AND ServiceName IN (${serviceName:singlequote})\r\n  AND ServiceName != 'loadgenerator'\r\nGROUP BY time, ServiceName\r\nORDER BY time ASC\r\nLIMIT 100000\r\n"
    }
   ]
  },
  {
   "title": "Error rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeInterval(Timestamp) as time,\r\n  count(*) as ` `,\r\n  ServiceName\r\nFROM otel_traces\r\nWHERE\r\n  $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id)\r\n  AND $__timeFilter(Timestamp)\r\n  AND ServiceName IN (${serviceName:singlequote})\r\n AND StatusCode IN ('Error', 'STATUS_CODE_ERROR')\r\n  AND ServiceName != 'loadgenerator' GROUP BY ServiceName, time\r\nORDER BY time ASC\r\nLIMIT 100000"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  min(Timestamp) as timestamp,\r\n  TraceId as `Trace ID`,\r\n  argMin(ServiceName, Timestamp) as `Service Name`,\r\n  divide(max(Duration), 1000000) as Duration\r\nFROM otel_traces\r\nWHERE\r\n  $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id)\r\n  AND ServiceName IN (${serviceName:singlequote})\r\n  AND ServiceName != 'loadgenerator'\r\n  AND $__timeFilter(Timestamp)\r\nGROUP BY TraceId\r\nORDER BY Duration DESC\r\nLIMIT 100\r\n"
    }
   ]
  },
  {
   "title": "Trace Details",
   "type": "traces",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "rawSql": "WITH '${trace_id}' as trace_id, (SELECT min(Start) FROM \"otel_traces_trace_id_ts\" WHERE TraceId = trace_id) as trace_start, (SELECT max(End) + 1 FROM \"otel_traces_trace_id_ts\" WHERE TraceId = trace_id) as trace_end SELECT \"TraceId\" as traceID, \"SpanId\" as spanID, \"ParentSpanId\" as parentSpanID, \"ServiceName\" as serviceName, \"SpanName\" as operationName, \"Timestamp\" as startTime, multiply(\"Duration\", 0.000001) as duration, arrayMap(key -> map('key', key, 'value',\"SpanAttributes\"[key]), mapKeys(\"SpanAttributes\")) as tags, arrayMap(key -> map('key', key, 'value',\"ResourceAttributes\"[key]), mapKeys(\"ResourceAttributes\")) as serviceTags FROM \"otel_traces\" WHERE traceID = trace_id AND startTime >= trace_start AND startTime <= trace_end AND ( Timestamp >= $__fromTime AND Timestamp <= $__toTime ) AND ( Duration > 0 ) ORDER BY Timestamp DESC, Duration DESC LIMIT 1000"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Trace Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT Timestamp as timestamp, Body as body, SeverityText as level FROM \"otel_logs\" LIMIT 1000"
    }
   ]
  }
 ]
}
{
 "title": "ClickHouse - Cluster Analysis",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "ClickHouse instance", "query": "grafana-clickhouse-datasource" },
   {
    "name": "database",
    "label": "Database",
    "query": "SELECT name FROM system.databases;"
   },
   { "name": "filters" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT version()" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT uptime() as uptime" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() as \"Number of databases\" FROM system.databases WHERE name IN (${database:singlequote})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() as \"Number of tables\" FROM system.tables WHERE database IN (${database:singlequote})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(total_rows) as \"Number of rows\" FROM system.tables WHERE database IN (${database:singlequote});"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() as \"Number of columns\" FROM system.columns WHERE database IN (${database:singlequote});"
    }
   ]
  },
  {
   "title": "Cluster Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT cluster, shard_num, replica_num, host_name, host_address, port, is_local, errors_count, slowdowns_count FROM system.clusters;\n"
    }
   ]
  },
  {
   "title": "Merge progress per table",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT concatAssumeInjective(database, '.', table) as db_table, round(100 * progress, 1) \"progress\" FROM system.merges WHERE database IN (${database:singlequote}) ORDER BY progress DESC LIMIT 5;\n"
    }
   ]
  },
  {
   "title": "Current merges",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT concatAssumeInjective(database, '.', table) as db_table, round(elapsed, 1) \"elapsed\", round(100 * progress, 1) \"progress\", is_mutation, partition_id, result_part_path, source_part_paths, num_parts, formatReadableSize(total_size_bytes_compressed) \"total_size_compressed\", formatReadableSize(bytes_read_uncompressed) \"read_uncompressed\", formatReadableSize(bytes_written_uncompressed) \"written_uncompressed\", columns_written, formatReadableSize(memory_usage) \"memory_usage\", thread_id FROM system.merges WHERE database IN (${database:singlequote});"
    }
   ]
  },
  {
   "title": "Mutations parts remaining",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT concatAssumeInjective(database, '.', table, ' - ', mutation_id) as db_table, length(parts_to_do_names) as parts_remaining FROM system.mutations WHERE parts_remaining > 0 AND database IN (${database:singlequote}) ORDER BY parts_remaining DESC;"
    }
   ]
  },
  {
   "title": "Current mutations",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT concatAssumeInjective(database, '.', table) as db_table, mutation_id, command, create_time, parts_to_do_names, is_done, latest_failed_part, if(latest_fail_time = '1970-01-01 00:00:00', 'success', 'failure') as success, if(latest_fail_time = '1970-01-01 00:00:00', '-', CAST(latest_fail_time, 'String')) as fail_time, latest_fail_reason FROM system.mutations WHERE database IN (${database:singlequote}) ORDER BY is_done ASC, create_time DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Replicated tables by delay",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT concatAssumeInjective(database, '.', table) as db_table, queue_size FROM system.replicas WHERE database IN (${database:singlequote}) ORDER BY absolute_delay DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Replicated tables by delay",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT concatAssumeInjective(database, '.', table) as db_table, is_leader, is_readonly, absolute_delay, queue_size, inserts_in_queue, merges_in_queue FROM system.replicas WHERE database IN (${database:singlequote}) ORDER BY absolute_delay DESC LIMIT 10"
    }
   ]
  }
 ]
}
{
 "title": "ClickHouse - Data Analysis",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "ClickHouse instance", "query": "grafana-clickhouse-datasource" },
   {
    "name": "database",
    "label": "Database",
    "query": "SELECT name FROM system.databases;\n"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "SELECT name FROM system.tables WHERE database IN (${database})"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT version()" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT uptime() as uptime" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  sum(total_rows) as \"Total rows\" FROM system.tables WHERE database IN (${database}) AND name IN (${table})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() as \"Total columns\" FROM system.columns WHERE database IN (${database}) AND table IN (${table})"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    name as Name,\n    path as Path,\n    formatReadableSize(free_space) as Free,\n    formatReadableSize(total_space) as Total,\n    1 - free_space/total_space as Used\nFROM system.disks"
    }
   ]
  },
  {
   "title": "Top tables by rows",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT concatAssumeInjective(table.database, '.', name) as name,\n       table_stats.total_rows as total_rows\nFROM system.tables table\n         LEFT JOIN ( SELECT table,\n       database,\n       sum(rows)                  as total_rows\nFROM system.parts\nWHERE table IN (${table}) AND active AND database IN (${database}) \nGROUP BY table, database\n ) AS table_stats ON table.name = table_stats.table AND table.database = table_stats.database\nORDER BY total_rows DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top tables by columns",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT concatAssumeInjective(table.database, '.', name) as name,\n       col_stats.col_count as total_columns\nFROM system.tables table\n         LEFT JOIN (SELECT database, table, count() as col_count FROM system.columns  GROUP BY table, database) as col_stats\n                   ON table.name = col_stats.table AND col_stats.database = table.database\nWHERE database IN (${database}) AND name != '' AND table IN (${table}) AND name != '' ORDER BY total_columns DESC LIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Database engines",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 4, "x": 15, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT engine, count() \"Number of databases\" FROM system.databases WHERE name IN (${database}) GROUP BY engine "
    }
   ]
  },
  {
   "title": "Table engines",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT engine, count() \"Number of tables\" FROM system.tables WHERE database IN (${database}) AND notLike(engine,'System%')  AND name IN (${table}) GROUP BY engine ORDER BY count() DESC"
    }
   ]
  },
  {
   "title": "Database summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT name,\n       engine,\n       tables,\n       partitions,\n       parts,\n       formatReadableSize(bytes_on_disk)            \"disk_size\",\n       col_count,\n       total_rows,\n       formatReadableSize(data_uncompressed_bytes) as \"uncompressed_size\"\nFROM system.databases db\n         LEFT JOIN ( SELECT database,\n                            uniq(table)                   \"tables\",\n                            uniq(table, partition)        \"partitions\",\n                            count()                    AS parts,\n                            sum(bytes_on_disk)            \"bytes_on_disk\",\n                            sum(data_uncompressed_bytes) as \"data_uncompressed_bytes\",\n                            sum(rows) as total_rows,\n                            max(col_count) as \"col_count\"\n                     FROM system.parts AS parts\n                               JOIN (SELECT database, count() as col_count\n                                         FROM system.columns\n                                         WHERE database IN (${database}) AND table IN (${table})\n                                         GROUP BY database) as col_stats\n                                        ON parts.database = col_stats.database\n                     WHERE database IN (${database}) AND active AND table IN (${table})\n                     GROUP BY database) AS db_stats ON db.name = db_stats.database\nWHERE database IN (${database}) AND lower(name) != 'information_schema'\nORDER BY bytes_on_disk DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Dictionaries",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT source, type, status, count() \"count\" FROM system.dictionaries GROUP BY source, type, status ORDER BY status DESC, source"
    }
   ]
  },
  {
   "title": "Table summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT name,\n       table.database,\n       engine,\n       partitions,\n       parts,\n       formatReadableSize(bytes_on_disk)            \"disk_size\",\n       col_count,\n       table_stats.total_rows,\n       formatReadableSize(data_uncompressed_bytes) as \"uncompressed_size\"\nFROM system.tables table\n         LEFT JOIN ( SELECT table,\n       database,\n       uniq(table, partition)        \"partitions\",\n       count()                    AS parts,\n       sum(bytes_on_disk)            \"bytes_on_disk\",\n       sum(data_uncompressed_bytes) as \"data_uncompressed_bytes\",\n       sum(rows)                  as total_rows,\n                            max(col_count) as col_count\nFROM system.parts as parts\n         LEFT JOIN (SELECT database, table, count() as col_count FROM system.columns GROUP BY table, database) as col_stats\n                   ON parts.table = col_stats.table AND col_stats.database = parts.database\nWHERE active\nGROUP BY table, database\n ) AS table_stats ON table.name = table_stats.table AND table.database = table_stats.database\nWHERE database IN (${database}) AND lower(name) != 'information_schema' AND table IN (${table})\nORDER BY bytes_on_disk DESC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Detached partitions",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT database, table, partition_id, name, disk, level FROM system.detached_parts WHERE database IN (${database}) AND table IN (${table})"
    }
   ]
  },
  {
   "title": "Parts over time with row count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT modification_time as timestamp, concatAssumeInjective(database, '.', table) as table, rows FROM system.parts parts WHERE parts.database IN ($database) AND parts.table IN (${table})  AND $__timeFilter(modification_time) ORDER BY modification_time ASC"
    }
   ]
  },
  {
   "title": "Max parts per partition",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT concatAssumeInjective(database, '.', table) as dbTable, count() \"partitions\", sum(part_count) \"parts\", max(part_count) \"max_parts_per_partition\"\nFROM ( SELECT database, table, count() \"part_count\"\n       FROM system.parts\n       WHERE database IN (${database}) AND active AND table IN (${table})\n       GROUP BY database, table, partition ) partitions\nGROUP BY database, table\nORDER BY max_parts_per_partition DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Recent part analysis",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT database, table, partition_id, modification_time, name, part_type, active, level, disk_name, path, marks, rows, bytes_on_disk, refcount, min_block_number, max_block_number FROM system.parts WHERE database IN (${database}) AND table IN (${table})  AND modification_time > now() - INTERVAL 3 MINUTE ORDER BY modification_time DESC"
    }
   ]
  }
 ]
}
{
 "title": "ClickHouse - Query Analysis",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "ClickHouse instance", "query": "grafana-clickhouse-datasource" },
   {
    "name": "query_kind",
    "label": "Query kind",
    "query": "SELECT DISTINCT(query_kind) as query_kind FROM system.query_log WHERE query_kind != ''"
   },
   {
    "name": "type",
    "label": "Query status",
    "query": "SELECT type FROM system.query_log GROUP BY type"
   },
   {
    "name": "user",
    "label": "User",
    "query": "SELECT DISTINCT(initial_user) FROM system.query_log WHERE initial_user != '' LIMIT 100"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() as \"Total queries\" FROM system.query_log WHERE type in ($type) AND initial_user IN ($user) AND query_kind IN ($query_kind) AND $__timeFilter(event_time) "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(memory_usage) as \"Avg query memory\", $__timeInterval(query_start_time) as time FROM system.query_log WHERE type in ($type) AND initial_user IN ($user) AND query_kind IN ($query_kind) AND $__timeFilter(event_time) GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "Query time distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT query_duration_ms as \"Query time\" FROM system.query_log WHERE type in ($type) AND initial_user IN ($user) AND query_kind IN ($query_kind) AND $__timeFilter(event_time) LIMIT 1000;"
    }
   ]
  },
  {
   "title": "Top users",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT initial_user, count() as c FROM system.query_log WHERE type in ($type) AND initial_user IN ($user) AND query_kind IN ($query_kind) GROUP BY initial_user LIMIT 100;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(query_duration_ms) as \"Avg query time\", $__timeInterval(query_start_time) as time FROM system.query_log WHERE type in ($type) AND initial_user IN ($user) AND query_kind IN ($query_kind) AND $__timeFilter(event_time) GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "Top query types over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(query_start_time) as time,\n       any(normalizeQuery(query)) AS normalized_query,\n       count() as c\nFROM system.query_log\nWHERE type != 'QueryStart'\n  AND $__timeFilter(event_time)\n  AND initial_user IN ($user)\n   AND query_kind IN ($query_kind)\n  AND normalized_query_hash IN (SELECT normalized_query_hash\n                                FROM system.query_log\n                                WHERE type in ($type) AND $__timeFilter(event_time) AND query_kind IN ($query_kind)\n                                GROUP BY normalized_query_hash\n                                ORDER BY count() DESC\n                                LIMIT 5)\nGROUP BY normalized_query_hash, time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Query performance by type over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(query_start_time) as time,\n       any(normalizeQuery(query)) AS normalized_query,\n       avg(query_duration_ms) as avg_query_duration\nFROM system.query_log\nWHERE type != 'QueryStart'\n  AND $__timeFilter(event_time)\n  AND type in ($type) AND initial_user IN ($user) AND query_kind IN ($query_kind)\n  AND normalized_query_hash IN (SELECT normalized_query_hash\n                                FROM system.query_log\n                                WHERE type in ($type) AND initial_user IN ($user) AND query_kind IN ($query_kind) AND $__timeFilter(event_time)\n                                GROUP BY normalized_query_hash\n                                ORDER BY avg(query_duration_ms) DESC\n                                LIMIT 10)\nGROUP BY normalized_query_hash, time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Query requests by user",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(query_start_time) as time, initial_user as user, count() as \"number of queries by\"\nFROM system.query_log\nWHERE query_kind IN ($query_kind) AND type IN ($type) AND $__timeFilter(event_time) AND initial_user IN (\n  SELECT initial_user\nFROM system.query_log\nWHERE query_kind IN ($query_kind) AND type IN ($type) AND $__timeFilter(event_time)\nGROUP BY initial_user\nORDER BY count() as c DESC\nLIMIT 10\n)\nGROUP BY initial_user, time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Memory usage over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(query_start_time) as time, \n      max(memory_usage) as \"Max Memory Usage\"\nFROM system.query_log\nWHERE $__timeFilter(event_time)\nGROUP BY time\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Read vs Write Rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(toDateTime(event_time), INTERVAL 60 second),  sum(read_rows) read_rows, sum(written_rows) written_rows FROM system.query_log WHERE $__timeFilter(event_time) GROUP BY event_time ORDER BY event_time ASC"
    }
   ]
  },
  {
   "title": "Query overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT query_start_time, type, query_duration_ms, initial_user, substring(query_id,1, 8) as query_id, query_kind, normalizeQuery(query) AS normalized_query, concat( toString(read_rows), ' rows / ', formatReadableSize(read_bytes) ) AS read, concat( toString(written_rows), ' rows / ', formatReadableSize(written_bytes) ) AS written, concat( toString(result_rows), ' rows / ', formatReadableSize(result_bytes) ) AS result, formatReadableSize(memory_usage) AS \"memory usage\" FROM system.query_log WHERE type in ($type) AND initial_user IN ($user) AND query_kind IN ($query_kind) AND $__timeFilter(event_time) ORDER BY query_duration_ms DESC LIMIT  1000"
    }
   ]
  }
 ]
}